-- Migration: attendance QR code feature

-- Toggle per-quiz: whether attendance scanning is required before starting
ALTER TABLE quizzes
  ADD COLUMN IF NOT EXISTS attendance_required BOOLEAN NOT NULL DEFAULT FALSE;

-- Short-lived tokens generated by the admin per quiz session
CREATE TABLE IF NOT EXISTS quiz_attendance_tokens (
  id            TEXT PRIMARY KEY,
  quiz_id       TEXT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  token         TEXT NOT NULL UNIQUE,
  expires_at    TIMESTAMPTZ NOT NULL,
  created_by    INT  NOT NULL REFERENCES users(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_attendance_tokens_quiz
  ON quiz_attendance_tokens(quiz_id);

-- Records which user checked in using which token
CREATE TABLE IF NOT EXISTS quiz_checkins (
  id            TEXT PRIMARY KEY,
  quiz_id       TEXT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  user_id       INT  NOT NULL REFERENCES users(id),
  token_id      TEXT REFERENCES quiz_attendance_tokens(id),
  checked_in_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(quiz_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_quiz_checkins_quiz
  ON quiz_checkins(quiz_id);
